jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - id: setup-haskell-cabal
        uses: "haskell-actions/setup@v2"
        with:
          ghc-version: "${{ matrix.ghc }}"
      - uses: "actions/cache@v3"
        with:
          key: "${{ runner.os }}-${{ matrix.ghc }}-cabal"
          path: "${{ steps.setup-haskell-cabal.outputs.cabal-store }}"
      - name: Install dependencies
        run: |
          cabal update
          cabal build all --enable-tests --enable-benchmarks --only-dependencies
      - name: build all
        run: cabal build all --enable-tests --enable-benchmarks
      - name: test all
        run: cabal test all --enable-tests
      - name: haddock all
        run: cabal haddock all
    strategy:
      matrix:
        ghc:
          - '9.6.2'
          - '9.4.5'
          - '9.2.8'
          - '9.0.2'
          - '8.10.7'
          - '8.8.4'
          - '8.6.5'
name: Haskell CI
on:
  - push
  - pull_request
